spring:
  application:
    name: elevateApi
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elevateapi
    username: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0
    password: 123456
server:
  port: 8080
  servlet:
#    设置请求路径的前缀，看到/api前缀，就知道要访问后端了
    context-path: /api
mybatis-plus:
  configuration:
#    （即开启了数据库字段下划线到Java实体类驼峰属性的自动转换），通常情况下是不需要在实体类属性上使用 @TableField 注解指定数据库字段名的
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

lxc:
  client:
    access-key: lxc
    secret-key: 12345